### ISSUE TITLE
supervise filename creation

### ISSUE THREAD

**Issue by ajschumacher** [editdata/editdata.org#31]
The app doesn't suggest that you give a `.json` or `.csv` extension to your files, but if you don't have such an extension, the app _does_ have a problem recognizing those files (re-opening them, etc.).

**Comment by sethvincent** [comment]
:+1:

**Comment by kvnneff** [comment]
Should the extension be required?  editdata.org doesn't care about the extension as far as saving the file, it mostly comes into play when trying to read the file.  If editdata.org is trying to read in a file and doesn't recognize the extension we could ask the user to specify.

**Comment by sethvincent** [comment]
Maybe the extension shouldn't be required, but by default could be suggested. I have my browser set to open a dialog box when downloading where i type a filename + extension, but not everybody has that option enabled. 

Particularly for the case where people have the save dialog box disabled in their browser, it's helpful to have the extension added to the filename by default. 

Sidenote: I meant to use something like this for reading the file & detecting the format: https://www.npmjs.com/package/detect-format

**Comment by kvnneff** [comment]
The app now appends the file extension automatically.  If users find themselves requiring different extensions when saving we can revisit this in the future.
